[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "/opt/homebrew/bin/solc"
solc_version = "0.8.19"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
